ansible_host: 192.168.56.104
ansible_ssh_user: andrey
ansible_ssh_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32383837323761663933373932666633306261396262616562383431646465376566343433376432
          6437376134353965653138663062323464336336316331610a336662646439613264346363336239
          36616464663436393830373734346662306532393164323331353863363364373165613831616534
          3739373032306632300a396333366338333963383732613766613738343161393032653465356338
          3831

ansible_sudo_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32383837323761663933373932666633306261396262616562383431646465376566343433376432
          6437376134353965653138663062323464336336316331610a336662646439613264346363336239
          36616464663436393830373734346662306532393164323331353863363364373165613831616534
          3739373032306632300a396333366338333963383732613766613738343161393032653465356338
          3831

ansible_python_interpreter: /usr/bin/python3
